Traceback (most recent call last):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/pyFirmata-1.1.0.dist-info/namespace_packages.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import find_packages
  File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.8/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3285, in _initialize_master_working_set
    tuple(
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3286, in <genexpr>
    dist.activate(replace=False)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2802, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2785, in _get_metadata
    if self.has_metadata(name):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1425, in has_metadata
    return self._has(path)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1623, in _has
    return os.path.exists(path)
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt
[  2%] Built target velodyne_msgs__cpp
[ 12%] Built target velodyne_msgs__rosidl_generator_c
[ 12%] Built target ament_cmake_python_copy_velodyne_msgs
[ 23%] Built target velodyne_msgs__rosidl_typesupport_cpp
[ 33%] Built target velodyne_msgs__rosidl_typesupport_fastrtps_cpp
[ 43%] Built target velodyne_msgs__rosidl_typesupport_fastrtps_c
[ 53%] Built target velodyne_msgs__rosidl_typesupport_introspection_cpp
[ 64%] Built target velodyne_msgs__rosidl_typesupport_introspection_c
[ 74%] Built target velodyne_msgs__rosidl_typesupport_c
[ 74%] Built target velodyne_msgs
[ 76%] Built target velodyne_msgs__py
[ 84%] Built target velodyne_msgs__rosidl_generator_py
[ 89%] Built target velodyne_msgs__rosidl_typesupport_c__pyext
[ 94%] Built target velodyne_msgs__rosidl_typesupport_introspection_c__pyext
[100%] Built target velodyne_msgs__rosidl_typesupport_fastrtps_c__pyext
make[2]: *** [CMakeFiles/ament_cmake_python_build_velodyne_msgs_egg.dir/build.make:70: CMakeFiles/ament_cmake_python_build_velodyne_msgs_egg] Interrupt
make[1]: *** [CMakeFiles/Makefile2:447: CMakeFiles/ament_cmake_python_build_velodyne_msgs_egg.dir/all] Interrupt
make: *** [Makefile:146: all] Interrupt
